### ISSUE TITLE
🚧[Front][Test] 테스트 Omok Json Server 

### ISSUE THREAD

**Issue by jlee38266** [beyond-sw-camp/be04-3rd-OmokNoonE-OmokFront#5]
### 테스트 유형 (Test Type)
- [x] 단위 테스트(Unit Test)
- [x] 기능 테스트(Functional Test)

### 변경 내용 (Changes)
모집글 목록 조회 및 특정 모집글을 조회를 테스트 하기 위한 json 파일을 업로드

### 수정된 테스트 내용 (Modified Test)
실제 서버의 연결 없이 json server만으로 필요한 데이터를 불러오기 위한 셋업을 만듭니다.

### 체크리스트 (Checklist)
- [x] 테스트 코드 추가 또는 수정 완료
- [x] 테스트 실행 및 결과 확인
- [x] 리뷰 요청

**Comment by jihyeongeun** [comment]
이상 없어보입니다:) 고생하셨습니다~
